{% set version = "2.0.0" %}

package:
  name: mock
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/m/mock/mock-{{ version }}.tar.gz
  md5: 0febfafd14330c9dcaa40de2d82d40ad

build:
  number: 1001
  script:
    ###########################################################
    # Delete broken symlink, which causes build to fail.      #
    # xref: https://github.com/testing-cabal/mock/issues/446  #
    ###########################################################
    - del /q docs\\changelog.txt  # [win and py27]
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pbr >=1.3

  run:
    - python
    - pbr >=1.3
    - funcsigs    # [py<33]
    - six

test:
  imports:
    - mock

about:
  home: https://github.com/testing-cabal/mock
  license: BSD 2-Clause
  license_file: LICENSE.txt
  summary: A library for testing in Python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
